from django.utils.translation import gettext_lazy as _
from kemelang import settings



LABEL_DICTIONARY = _('Dictionary')

LABEL_COUNTRY = _('Country')
LABEL_COUNTRY_PLURAL = _('Countries')
LABEL_NO_COUNTRY = _('No countries')
LABEL_COUNTRY_ACTION_ADD = _('Add country')

LABEL_LANGAGE = _('Langage')
LABEL_LANGAGE_PLURAL = _('Langages')
LABEL_NO_LANGAGE = _('No langages')
LABEL_LANGAGE_ACTION_ADD = _('Add langage')

LABEL_WORD = _('Word')
LABEL_WORD_TYPE = _('Word Type')
LABEL_WORD_PLURAL = _('Words')
LABEL_NO_WORD = _('No words')
LABEL_WORD_ACTION_ADD = _('Add word')

LABEL_EXAMPLE = _('Example')
LABEL_EXAMPLE_PLURAL = _('Examples')
LABEL_NO_EXAMPLE = _('No example')
LABEL_EXAMPLE_ACTION_ADD = _('Add example')
LABEL_EXAMPLE_CONTRIBUTE = _('Contribute by adding examples')

LABEL_SYNONYME = _('Synonyme')
LABEL_SYNONYME_PLURAL = _('Synonymes')
LABEL_NO_SYNONYME = _('No synonymes')
LABEL_SYNONYME_CONTRIBUTE = _('Contribute by adding synonymes')

LABEL_DESCRIPTION = _('Description')
LABEL_DEFINITION = _('Definition')
LABEL_TRANSLITERATION = _('Transliteration')

LABEL_VOCABULARY = _('Vocabulary')
LABEL_VOCABULARY_PLURAL = _('Vocabularies')


LABEL_TRANSLATION = _('Translation')
LABEL_TRANSLATION_PLURAL = _('Translations')
LABEL_NO_TRANSLATION = _('No translations')
LABEL_TRANSLATION_CONTRIBUTE = _('Contribute by adding translations')

LABEL_CONTRIBUTE = _('Contribute')
LABEL_TRANSLATE_INVITE = _('Enter word')
LABEL_SEARCH_LANGAGE = _('Search langages')
LABEL_AUTO_DETECT = _('Auto Detect')



DASHBOARD_DASHBOARD_TITLE = _('Dashboard')
DASHBOARD_TRANSLATOR_TITLE = _('Translator')

DASHBOARD_INFOS_TITLE                 = _('Infos')
DASHBOARD_INFO_TITLE                  = _('Info')
DASHBOARD_INFO_CREATE_TITLE           = _('New Info')
DASHBOARD_INFO_UPDATE_TITLE           = _('Info Update')

DASHBOARD_GROUPS_TITLE                 = _('Groups')
DASHBOARD_GROUP_TITLE                  = _('Group')
DASHBOARD_GROUP_CREATE_TITLE           = _('New Group')
DASHBOARD_GROUP_UPDATE_TITLE           = _('Group Update')


DASHBOARD_HIGHLIGHTS_TITLE                  = _('Highlights')
DASHBOARD_HIGHLIGHT_TITLE                 = _('Highlight')
DASHBOARD_HIGHLIGHT_UPDATE_TITLE           = _('Highlight Update')
DASHBOARD_HIGHLIGHT_CREATE_TITLE           = _('New Highlight')

DASHBOARD_CAMPAIGNS_TITLE               = _('Campaigns')
DASHBOARD_CAMPAIGN_UPDATE_TITLE               = _('Campaign Update')
DASHBOARD_CAMPAIGN_CREATE_TITLE               = _('Campaign Create')
DASHBOARD_CAMPAIGN_TITLE               = _('Campaign')


DASHBOARD_USERS_TITLE = _('Users')
DASHBOARD_CUSTOMERS_TITLE = _('Customers')
DASHBOARD_SELLERS_TITLE = _('Sellers')
DASHBOARD_USER_TITLE = _('User')
DASHBOARD_USER_UPDATE_TITLE = _('User Update')
DASHBOARD_USER_CREATE_TITLE = _('New User')


DASHBOARD_TOKENS_TITLE = _('Tokens')
DASHBOARD_PARTNER_TOKENS_TITLE = _('Partner Tokens')
DASHBOARD_TOKEN_CREATE_TITLE = _('New Token')

DASHBOARD_REPORTS_TITLE = _('Reports')
LABEL_NEW = _('New')
LABEL_NEW_UPPERCASE = _('NEW')

REQUEST_ERROR = _('Error on the request')
INVALID_FORM = _('Invalid Submitted data')


UI_BANNER_DESCRIPTION = _("Your online dictionary for african langages")

UI_CONTACT_SUBJECT = _('Need more information')
UI_CONTACT_BODY = _('Hello, I have a question about the dictionary.')
UI_INVALID_USER_REQUEST = _('Invalid user request')
UI_RESOURCE_NOT_FOUND_TITLE = _('Resource not found !')
UI_RESOURCE_NOT_FOUND = _('The resource you requested does not exist or is no longer available.')
UI_400_TITLE = _('Bad Request')
UI_400 = _('You submitted a bad request.')
UI_404_TITLE = UI_RESOURCE_NOT_FOUND_TITLE
UI_404 = UI_RESOURCE_NOT_FOUND
UI_403_TITLE = _('Access Forbidden')
UI_403 = _('You can not access this page.')

UI_500_TITLE = _('Server Error')
UI_500 = _('Oups ! There is an intern error. If the errors persists please informe our team through our contact.')
UI_GO_TO_QUIZ = _('Go to QUIZ-Home')
UI_HOME_PAGE = _('KEMELANG')
UI_HOME_MAINTENANCE_PAGE = _('KEMELANG IS COMING')
UI_CAMPAIGN_CREATE_BTN_LABEL = _('Create Campaign')
UI_CAMPAIGN_IMAGE_TITLE = _('Campaign Image')
UI_ADD_BTN_LABEL = _('Add')
UI_BACK_BTN_LABEL = _('Back')
UI_CREATE_BTN_LABEL = _('Create')
UI_UPDATE_BTN_LABEL = _('Update')
UI_CANCEL_BTN_LABEL = _('Cancel')
UI_SEND_BTN_LABEL   = _('Send')
UI_OPEN_BTN_LABEL   = _('Open')
UI_CLOSE_BTN_LABEL = _('Close')
UI_SEO_HOME = _('African dictionary')
UI_FOOTER_LABEL = _('Online African Dictionary')
UI_ENTER_WORD_FORM_INVITE = _('Enter word ...')
UI_SPACE_KEY_LABEL = _('Space')
UI_BACKSPACE_KEY_LABEL = _('Backspace')
UI_NO_RESULT = _('No results')
UI_LOGIN_LABEL = _('Login')
UI_SIGNIN_LABEL = _('Sign In')
UI_LOGOUT_LABEL = _('Logout')
UI_SIGNOUT_LABEL = _('Sign Out')
UI_SIGN_UP_LABEL = _('Sign Up')
UI_ACCOUNT_LABEL = _('My Account')

UI_STRINGS_CONTEXT = {
    
    'UI_BANNER_DESCRIPTION': UI_BANNER_DESCRIPTION,
    'UI_CAMPAIGN_CREATE_BTN_LABEL': UI_CAMPAIGN_CREATE_BTN_LABEL,
    'UI_CAMPAIGN_IMAGE_TITLE': UI_CAMPAIGN_IMAGE_TITLE,
    'UI_CONTACT_SUBJECT': UI_CONTACT_SUBJECT,
    'UI_CONTACT_BODY': UI_CONTACT_BODY,
    'UI_HOME_MAINTENANCE_PAGE': UI_HOME_MAINTENANCE_PAGE,
    'UI_RESOURCE_NOT_FOUND': UI_RESOURCE_NOT_FOUND,
    'UI_GO_TO_QUIZ': UI_GO_TO_QUIZ,
    'UI_HOME_PAGE': UI_HOME_PAGE,
    'UI_RESOURCE_NOT_FOUND_TITLE': UI_RESOURCE_NOT_FOUND_TITLE,
    'UI_400_TITLE': UI_400_TITLE,
    'UI_400': UI_400,
    'UI_403_TITLE' : UI_403_TITLE,
    'UI_403': UI_403,
    'UI_404_TITLE': UI_404_TITLE,
    'UI_404': UI_404,
    'UI_500_TITLE': UI_500_TITLE,
    'UI_500': UI_500,
    'UI_ADD_BTN_LABEL':UI_ADD_BTN_LABEL,
    'UI_BACK_BTN_LABEL': UI_BACK_BTN_LABEL,
    'UI_CREATE_BTN_LABEL' : UI_CREATE_BTN_LABEL,
    'UI_UPDATE_BTN_LABEL': UI_UPDATE_BTN_LABEL,
    'UI_CANCEL_BTN_LABEL': UI_CANCEL_BTN_LABEL,
    'UI_CLOSE_BTN_LABEL': UI_CLOSE_BTN_LABEL, 
    'UI_SEND_BTN_LABEL'  : UI_SEND_BTN_LABEL,
    'UI_OPEN_BTN_LABEL': UI_OPEN_BTN_LABEL,
    'UI_SPACE_KEY_LABEL': UI_SPACE_KEY_LABEL,
    'UI_BACKSPACE_KEY_LABEL': UI_BACKSPACE_KEY_LABEL,
    'UI_SEO_HOME': UI_SEO_HOME,
    'UI_ENTER_WORD_FORM_INVITE': UI_ENTER_WORD_FORM_INVITE,
    'UI_FOOTER_LABEL': UI_FOOTER_LABEL,
    'UI_NO_RESULT': UI_NO_RESULT,
    'UI_LOGIN_LABEL': UI_LOGIN_LABEL,
    'UI_SIGNIN_LABEL': UI_SIGNIN_LABEL,
    'UI_LOGOUT_LABEL': UI_LOGOUT_LABEL,
    'UI_SIGNOUT_LABEL': UI_SIGNOUT_LABEL,
    'UI_SIGN_UP_LABEL': UI_SIGN_UP_LABEL,
    'UI_ACCOUNT_LABEL': UI_ACCOUNT_LABEL,
    'REQUEST_ERROR': REQUEST_ERROR,
    'INVALID_FORM': INVALID_FORM,
    'DASHBOARD_DASHBOARD_TITLE': DASHBOARD_DASHBOARD_TITLE,
    'DASHBOARD_TRANSLATOR_TITLE': DASHBOARD_TRANSLATOR_TITLE,
    'DASHBOARD_INFOS_TITLE': DASHBOARD_INFOS_TITLE,
    'DASHBOARD_INFO_TITLE': DASHBOARD_INFO_TITLE,
    'DASHBOARD_INFO_CREATE_TITLE': DASHBOARD_INFO_CREATE_TITLE,
    'DASHBOARD_INFO_UPDATE_TITLE': DASHBOARD_INFO_UPDATE_TITLE,
    'DASHBOARD_GROUPS_TITLE': DASHBOARD_GROUPS_TITLE,
    'DASHBOARD_GROUP_TITLE': DASHBOARD_GROUP_TITLE,
    'DASHBOARD_GROUP_CREATE_TITLE': DASHBOARD_GROUP_CREATE_TITLE,
    'DASHBOARD_GROUP_UPDATE_TITLE': DASHBOARD_GROUP_UPDATE_TITLE,
    'DASHBOARD_USERS_TITLE': DASHBOARD_USERS_TITLE,
    'DASHBOARD_USER_TITLE': DASHBOARD_USER_TITLE,
    'DASHBOARD_USER_UPDATE_TITLE': DASHBOARD_USER_UPDATE_TITLE,
    'DASHBOARD_USER_CREATE_TITLE': DASHBOARD_USER_CREATE_TITLE,
    'DASHBOARD_TOKENS_TITLE': DASHBOARD_TOKENS_TITLE,
    'DASHBOARD_PARTNER_TOKENS_TITLE': DASHBOARD_PARTNER_TOKENS_TITLE,
    'DASHBOARD_TOKEN_CREATE_TITLE': DASHBOARD_TOKEN_CREATE_TITLE,
    'LABEL_DICTIONARY': LABEL_DICTIONARY,
    'LABEL_COUNTRY': LABEL_COUNTRY,
    'LABEL_COUNTRY_PLURAL':LABEL_COUNTRY_PLURAL,
    'LABEL_NO_COUNTRY': LABEL_NO_COUNTRY,
    'LABEL_COUNTRY_ACTION_ADD': LABEL_COUNTRY_ACTION_ADD,
    'LABEL_LANGAGE': LABEL_LANGAGE,
    'LABEL_LANGAGE_PLURAL': LABEL_LANGAGE_PLURAL,
    'LABEL_NO_LANGAGE': LABEL_NO_LANGAGE,
    'LABEL_LANGAGE_ACTION_ADD': LABEL_LANGAGE_ACTION_ADD,
    'LABEL_WORD': LABEL_WORD,
    'LABEL_WORD_TYPE': LABEL_WORD_TYPE,
    'LABEL_WORD_PLURAL': LABEL_WORD_PLURAL,
    'LABEL_NO_WORD': LABEL_NO_WORD,
    'LABEL_WORD_ACTION_ADD': LABEL_WORD_ACTION_ADD,
    'LABEL_EXAMPLE': LABEL_EXAMPLE,
    'LABEL_EXAMPLE_PLURAL': LABEL_EXAMPLE_PLURAL,
    'LABEL_NO_EXAMPLE': LABEL_NO_EXAMPLE,
    'LABEL_EXAMPLE_ACTION_ADD': LABEL_EXAMPLE_ACTION_ADD,
    'LABEL_EXAMPLE_CONTRIBUTE': LABEL_EXAMPLE_CONTRIBUTE,
    'LABEL_SYNONYME': LABEL_SYNONYME,
    'LABEL_SYNONYME_PLURAL': LABEL_SYNONYME_PLURAL,
    'LABEL_NO_SYNONYME': LABEL_NO_SYNONYME,
    'LABEL_SYNONYME_CONTRIBUTE': LABEL_SYNONYME_CONTRIBUTE,
    'LABEL_DESCRIPTION': LABEL_DESCRIPTION,
    'LABEL_VOCABULARY': LABEL_VOCABULARY,
    'LABEL_VOCABULARY_PLURAL': LABEL_VOCABULARY_PLURAL,
    'LABEL_TRANSLATION': LABEL_TRANSLATION,
    'LABEL_TRANSLATION_PLURAL': LABEL_TRANSLATION_PLURAL,
    'LABEL_NO_TRANSLATION': LABEL_NO_TRANSLATION,
    'LABEL_TRANSLATION_CONTRIBUTE': LABEL_TRANSLATION_CONTRIBUTE,
    'LABEL_CONTRIBUTE': LABEL_CONTRIBUTE,
    'LABEL_TRANSLATE_INVITE': LABEL_TRANSLATE_INVITE,
    'LABEL_SEARCH_LANGAGE': LABEL_SEARCH_LANGAGE,
    'LABEL_AUTO_DETECT': LABEL_AUTO_DETECT,
    'LABEL_DEFINITION': LABEL_DEFINITION,
    'LABEL_TRANSLITERATION': LABEL_TRANSLITERATION
}