

MAX_RECENT = 5
TOP_VIEWS_MAX = 10
EMAIL_VALIDATION_DELAY = 5 #days
CELERY_LOGGER_HANDLER_NAME = "async"
CELERY_LOGGER_NAME = "async"
CELERY_FILE_HANDLER_CONF = {
	'level': 'INFO',
	'class': 'logging.handlers.TimedRotatingFileHandler',
	'formatter': 'file',
	'filename':'logs/kemelang.log',
	'when' : 'midnight'
}


ABTEST_ACTION_MENU_CLICKED = 0
ABTEST_ACTION_LOGIN_CLICKED = 1
ABTEST_ACTION_SITE_CLICKED = 2
ABTEST_ACTION_REGISTER_CLICKED = 3

ABTEST_ACTIONS = (
    (ABTEST_ACTION_MENU_CLICKED, 'MOBILE MENU CLICKED'),
    (ABTEST_ACTION_LOGIN_CLICKED, 'LOGIN BTN CLICKED'),
    (ABTEST_ACTION_SITE_CLICKED, 'SITE LOGO CLICKED'),
    (ABTEST_ACTION_REGISTER_CLICKED, 'REGISTER BTN CLICKED'),
)